version: "3.8"
services:
  database:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ngrinder_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci",  "--lower_case_table_names=1"]
  controller:
    image: ngrinder/controller:3.5.8
    container_name: ngrinder-controller
    ports:
      - "80:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder/controller:/opt/ngrinder-controller
  agent-1:
    image: ngrinder/agent:3.5.8
    container_name: ngrinder-agent-1
    volumes:
      - ./ngrinder/agent-1:/opt/ngrinder-agent
    command: [ "ngrinder-controller:80" ]
  agent-2:
    image: ngrinder/agent:3.5.8
    container_name: ngrinder-agent-2
    volumes:
      - ./ngrinder/agent-2:/opt/ngrinder-agent
    command: [ "ngrinder-controller:80" ]

